# Generated by Django 4.2.13 on 2024-06-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_id',
            field=models.IntegerField(unique=True, verbose_name='ID объявления'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор объявления'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='position',
            field=models.IntegerField(verbose_name='Позиция объявления'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='views',
            field=models.IntegerField(verbose_name='Кол-во просмотров объявления'),
        ),
    ]
